spring:
  application:
    name: food-ordering-system
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering_system_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG

thread:
  config:
    time-sleep-in-millis: 200
    retries: 3